---
- name: apt upgrade 実行
  hosts: rpi5
  become: yes

  tasks:
    - name: noble-updates が無い場合に Suites へ追加
      replace:
        path: /etc/apt/sources.list.d/ubuntu.sources
        regexp: '^Suites:\s*noble$'
        replace: 'Suites: noble noble-updates'
      tags:
        - noble-updates-repo

    - name: パッケージリスト更新
      apt:
        update_cache: yes

    - name: パッケージアップグレード
      apt:
        upgrade: dist

    - name: 不要パッケージ削除
      apt:
        autoremove: yes
